#!/bin/bash

package_name="libxml2"
package_version="2.13.6"
package_address="https://download.gnome.org/sources/$package_name/2.13/$package_name-$package_version.tar.xz"
package_dependencies=""

function do_configure
{
    "$package_source/configure"                                  \
        --prefix="/usr"                                          \
        --docdir="/usr/share/doc/$package_name-$package_version" \
        --disable-static                                         \
        --sysconfdir="/etc"                                      \
        --with-history                                           \
        --with-icu                                               \
        PYTHON="/usr/bin/python3"
}

function do_build
{
    make
}

function do_install
{
    make DESTDIR="$package_root" install
}
