#!/bin/bash

package_name="flit-core"
package_version="3.11.0"
package_address="https://pypi.org/packages/source/f/$package_name/flit_core-$package_version.tar.gz"
package_dependencies=""

function do_configure
{
    pip3 wheel "$package_source" \
        --no-build-isolation     \
        --no-cache-dir           \
        --no-deps                \
        --wheel-dir "$package_build"
}

function do_build
{
    return
}

function do_install
{
    pip3 install "flit_core"          \
        --find-links "$package_build" \
        --no-index                    \
        --root="$package_root"
}
