#!/bin/bash

package_name="linux"
package_version="6.13.4"
package_address="https://www.kernel.org/pub/linux/kernel/v6.x/$package_name-$package_version.tar.gz"
package_dependencies=""

function do_configure
{
    make --directory "$package_source" x86_64_defconfig
}

function do_build
{
    make --directory "$package_source"
}

function do_install
{
    make --directory "$package_source"    \
        INSTALL_PATH="$package_root/boot" \
        INSTALL_MOD_PATH="$package_root"  \
            install modules_install
}
