#!/bin/bash

package_name="glibc"
package_version="2.41"
package_address="https://ftp.gnu.org/gnu/$package_name/$package_name-$package_version.tar.gz"

function do_configure
{
    ln --symbolic "$toolchain_root/lib/ld-linux-x86-64.so.2" \
       --relative "$toolchain_root/lib64"

    echo "rootsbindir=/usr/sbin" > "$package_build/configparms"

    "$package_source/configure"                        \
        --prefix="/usr"                                \
        --build=`$package_source/scripts/config.guess` \
        --host="$toolchain_target"                     \
        --with-headers="$toolchain_root/usr/include"   \
        --disable-nscd                                 \
        --enable-kernel="5.4"                          \
        libc_cv_slibdir="/usr/lib"
}

function do_build
{
    make
}

function do_install
{
    make DESTDIR="$toolchain_root" install

    sed "/RTLDLIST=/s@/usr@@g" --in-place "$toolchain_root/usr/bin/ldd"
}
