#!/bin/bash

package_name="diffutils"
package_version="3.11"
package_address="https://ftp.gnu.org/gnu/$package_name/$package_name-$package_version.tar.gz"

function do_configure
{
    "$package_source/configure"                          \
        --prefix="/usr"                                  \
        --build=`$package_source/build-aux/config.guess` \
        --host="$toolchain_target"
}

function do_build
{
    make
}

function do_install
{
    make DESTDIR="$toolchain_root" install
}
