#!/bin/bash

package_name="wget"
package_version="1.25.0"
package_address="https://ftp.gnu.org/gnu/$package_name/$package_name-$package_version.tar.gz"

function do_configure
{
    "$package_source/configure"                          \
        --prefix="/usr"                                  \
        --build=`$package_source/build-aux/config.guess` \
        --host="$toolchain_target"                       \
        --with-ssl="openssl"                             \
        OPENSSL_CFLAGS="-I$toolchain_root/usr/include"   \
        OPENSSL_LIBS="-L$toolchain_root/usr/lib -lssl -lcrypto"
}

function do_build
{
    make
}

function do_install
{
    make DESTDIR="$toolchain_root" install
}
