#!/bin/bash

package_name="zlib"
package_version="1.3.1"
package_address="https://zlib.net/$package_name-$package_version.tar.gz"

function do_configure
{
    CROSS_PREFIX="$toolchain_target-" "$package_source/configure" \
        --prefix="/usr"
}

function do_build
{
    make
}

function do_install
{
    make DESTDIR="$toolchain_root" install

    rm "$toolchain_root/usr/lib/libz.a"
}
