#!/bin/bash

package_name="zlib"
package_version="1.3.1"
package_address="https://zlib.net/fossils/$package_name-$package_version.tar.gz"
package_dependencies=""

function do_configure
{
    "$package_source/configure" \
        --prefix="/usr"
}

function do_build
{
    make
}

function do_install
{
    make DESTDIR="$package_root" install

    rm "$package_root/usr/lib/libz.a"
}
