#!/bin/bash

package_name="zstd"
package_version="1.5.7"
package_address="https://github.com/facebook/$package_name/releases/download/v$package_version/$package_name-$package_version.tar.gz"
package_dependencies=""

function do_configure
{
    make --directory="$package_source" prefix="/usr"
}

function do_build
{
    return
}

function do_install
{
    make --directory="$package_source" prefix="/usr" DESTDIR="$package_root" install

    rm "$package_root/usr/lib/libzstd.a"
}
