#!/bin/bash

package_name="docutils"
package_version="0.21.2"
package_address="https://files.pythonhosted.org/packages/source/d/$package_name/$package_name-$package_version.tar.gz"
package_dependencies=""

function do_configure
{
    pip3 wheel "$package_source" \
        --no-build-isolation     \
        --no-cache-dir           \
        --no-deps                \
        --wheel-dir "$package_build"
}

function do_build
{
    return
}

function do_install
{
    pip3 install "docutils"           \
        --find-links "$package_build" \
        --no-index                    \
        --root="$package_root"
}
