#!/bin/bash

package_name="libinput"
package_version="0.5.0"
package_address="http://www.freedesktop.org/software/$package_name/$package_name-$package_version.tar.xz"
package_dependencies=""

function do_configure
{
    "$package_source/configure" \
        --prefix="/usr"         \
        --disable-static
}

function do_build
{
    make
}

function do_install
{
    make DESTDIR="$package_root" install
}
