#!/bin/bash

package_name="bash"
package_version="5.2.37"
package_address="https://ftp.gnu.org/gnu/$package_name/$package_name-$package_version.tar.gz"
package_dependencies=""

function do_configure
{
    "$package_source/configure"   \
        --prefix="/usr"           \
        --with-installed-readline \
        --without-bash-malloc
}

function do_build
{
    make
}

function do_install
{
    make DESTDIR="$package_root" install
}
