#!/bin/bash

package_name="harfbuzz"
package_version="10.4.0"
package_address="https://github.com/harfbuzz/$package_name/releases/download/$package_version/$package_name-$package_version.tar.xz"
package_dependencies=""

function do_configure
{
    meson setup "$package_source" \
        --prefix="/usr"           \
        --libdir="/usr/lib"       \
        --buildtype="release"     \
        -D graphite2="enabled"
}

function do_build
{
    ninja
}

function do_install
{
    DESTDIR="$package_root" ninja install
}
