#!/bin/bash

package_name="sysvinit"
package_version="3.14"
package_address="https://github.com/slicer69/$package_name/releases/download/$package_version/$package_name-$package_version.tar.xz"
package_dependencies=""

function do_configure
{
    return
}

function do_build
{
    make --directory "$package_source"
}

function do_install
{
    make --directory "$package_source" DESTDIR="$package_root" install
}
