#!/bin/bash

package_name="libxkbcommon"
package_version="1.8.0"
package_address="https://github.com/lfs-book/$package_name/archive/v$package_version/$package_name-$package_version.tar.gz"
package_dependencies=""

function do_configure
{
    meson setup "$package_source" \
        --prefix="/usr"           \
        --libdir="/usr/lib"       \
        --buildtype="release"     \
        -D enable-docs="false"    \
        -D enable-x11="false"
}

function do_build
{
    ninja
}

function do_install
{
    DESTDIR="$package_root" ninja install
}
