#!/bin/bash

package_name="meson"
package_version="1.7.0"
package_address="https://github.com/mesonbuild/$package_name/archive/refs/tags/$package_version.tar.gz"
package_dependencies=""

function do_configure
{
    pip3 wheel "$package_source" \
        --no-build-isolation     \
        --no-cache-dir           \
        --no-deps                \
        --wheel-dir "$package_build"
}

function do_build
{
    return
}

function do_install
{
    pip3 install "meson"              \
        --find-links "$package_build" \
        --no-index                    \
        --root="$package_root"
}
