#!/bin/bash

package_name="procps-ng"
package_version="4.0.5"
package_address="https://sourceforge.net/projects/$package_name/files/Production/$package_name-$package_version.tar.xz"
package_dependencies=""

function do_configure
{
    "$package_source/configure"                                  \
        --prefix="/usr"                                          \
        --docdir="/usr/share/doc/$package_name-$package_version" \
        --disable-kill                                           \
        --disable-static                                         \
        --enable-watch8bit
}

function do_build
{
    make
}

function do_install
{
    make DESTDIR="$package_root" install
}
