#!/bin/bash

package_name="libxcrypt"
package_version="4.4.38"
package_address="https://github.com/besser82/$package_name/releases/download/v$package_version/$package_name-$package_version.tar.xz"
package_dependencies=""

function do_configure
{
    "$package_source/configure"        \
        --prefix="/usr"                \
        --disable-failure-tokens       \
        --disable-static               \
        --enable-hashes="strong,glibc" \
        --enable-obsolete-api="no"
}

function do_build
{
    make
}

function do_install
{
    make DESTDIR="$package_root" install
}
