#!/bin/bash

package_name="shadow"
package_version="4.17.3"
package_address="https://github.com/shadow-maint/$package_name/releases/download/$package_version/$package_name-$package_version.tar.gz"
package_dependencies=""

function do_configure
{
    "$package_source/configure" \
        --prefix="/usr"         \
        --disable-static        \
        --without-libbsd
}

function do_build
{
    make
}

function do_install
{
    make DESTDIR="$package_root" install
}
