#!/bin/bash

package_name="expat"
package_version="2.7.1"
package_address="https://prdownloads.sourceforge.net/$package_name/$package_name-$package_version.tar.gz"
package_dependencies=""

function do_configure
{
    "$package_source/configure"                                  \
        --prefix="/usr"                                          \
        --docdir="/usr/share/doc/$package_name-$package_version" \
        --disable-static
}

function do_build
{
    make
}

function do_install
{
    make DESTDIR="$package_root" install
}
