#!/bin/bash

package_name="python"
package_version="3.13.2"
package_address="https://www.python.org/ftp/$package_name/$package_version/Python-$package_version.tgz"
package_dependencies=""

function do_configure
{
    "$package_source/configure" \
        --prefix="/usr"         \
        --enable-optimizations  \
        --enable-shared         \
        --with-system-expat
}

function do_build
{
    make
}

function do_install
{
    make DESTDIR="$package_root" install
}
