#!/bin/bash

package_name="libjpeg-turbo"
package_version="3.0.1"
package_address="https://downloads.sourceforge.net/$package_name/$package_name-$package_version.tar.gz"
package_dependencies=""

function do_configure
{
    cmake "$package_source"                        \
        -D CMAKE_INSTALL_PREFIX="/usr"             \
        -D CMAKE_INSTALL_DEFAULT_LIBDIR="/usr/lib" \
        -D CMAKE_BUILD_TYPE="RELEASE"              \
        -D CMAKE_SKIP_INSTALL_RPATH="ON"           \
        -D ENABLE_STATIC="FALSE"
}

function do_build
{
    make
}

function do_install
{
    make DESTDIR="$package_root" install
}
