#!/bin/bash

package_name="file"
package_version="5.46"
package_address="https://astron.com/pub/$package_name/$package_name-$package_version.tar.gz"
package_dependencies=""

function do_configure
{
    "$package_source/configure" \
        --prefix="/usr"
}

function do_build
{
    make
}

function do_install
{
    make DESTDIR="$package_root" install
}
