#!/bin/bash

package_name="xz"
package_version="5.6.4"
package_address="https://github.com/tukaani-project/$package_name/releases/download/v$package_version/$package_name-$package_version.tar.xz"
package_dependencies=""

function do_configure
{
    "$package_source/configure"                                  \
        --prefix="/usr"                                          \
        --docdir="/usr/share/doc/$package_name-$package_version" \
        --disable-static
}

function do_build
{
    make
}

function do_install
{
    make DESTDIR="$package_root" install
}
