#!/bin/bash

package_name="wlroots"
package_version="0.18.2"
package_address="https://gitlab.freedesktop.org/wlroots/$package_name/-/releases/$package_version/downloads/$package_name-$package_version.tar.gz"
package_dependencies=""

function do_configure
{
    meson setup "$package_source" \
        --prefix="/usr"           \
        --libdir="/usr/lib"       \
        --buildtype="release"
}

function do_build
{
    ninja
}

function do_install
{
    DESTDIR="$package_root" ninja install
}
