#!/bin/bash

package_name="libevdev"
package_version="1.13.3"
package_address="http://www.freedesktop.org/software/$package_name/$package_name-$package_version.tar.xz"
package_dependencies=""

function do_configure
{
    meson setup "$package_source"   \
        --prefix="/usr"             \
        --libdir="/usr/lib"         \
        --buildtype="release"       \
        -D documentation="disabled" \
        -D tests="disabled"
}

function do_build
{
    ninja
}

function do_install
{
    DESTDIR="$package_root" ninja install
}
