#!/bin/bash

package_name="pcre2"
package_version="10.45"
package_address="https://github.com/PCRE2Project/$package_name/releases/download/$package_name-$package_version/$package_name-$package_version.tar.gz"
package_dependencies=""

function do_configure
{
    "$package_source/configure"                                  \
        --prefix="/usr"                                          \
        --docdir="/usr/share/doc/$package_name-$package_version" \
        --disable-static                                         \
        --enable-jit                                             \
        --enable-pcre2-16                                        \
        --enable-pcre2-32                                        \
        --enable-pcre2grep-libz                                  \
        --enable-unicode
}

function do_build
{
    make
}

function do_install
{
    make DESTDIR="$package_root" install
}
