#!/bin/bash

package_name="kmod"
package_version="34"
package_address="https://www.kernel.org/pub/linux/utils/kernel/$package_name/$package_name-$package_version.tar.xz"
package_dependencies=""

function do_configure
{
    meson setup "$package_source" \
        --prefix="/usr"           \
        --libdir="/usr/lib"       \
        --sbindir="/usr/sbin"     \
        --buildtype="release"     \
        -D manpages="false"
}

function do_build
{
    ninja
}

function do_install
{
    DESTDIR="$package_root" ninja install
}
