#!/bin/bash

function directory
{
    directory="$(realpath "$0" | xargs dirname)"
}

function toolchain_target
{
    toolchain_target="$(uname -m)-toolchain-linux-gnu"
}

function toolchain_root
{
    toolchain_root="$directory/toolchain/root"

    if [ ! -d "$toolchain_root" ]
    then
        for toolchain_directory in \
            "etc"                  \
            "usr/bin"              \
            "usr/lib"              \
            "usr/lib64"            \
            "usr/sbin"             \
            "root"
        do
            if [ ! -d "$toolchain_root/$toolchain_directory" ]
            then
                mkdir --parents "$toolchain_root/$toolchain_directory"
            fi
        done

        for toolchain_directory in "bin" "lib" "lib64" "sbin"
        do
            if [ ! -L "$toolchain_root/$toolchain_directory" ]
            then
                ln --symbolic "$toolchain_root/usr/$toolchain_directory" \
                   --relative "$toolchain_root"
            fi
        done
    fi
}

function toolchain_hostname
{
    echo "toolchain" > "$toolchain_root/etc/hostname"

	cat <<- EOF > "$toolchain_root/etc/hosts"
		127.0.0.1 localhost toolchain
	EOF
}

function toolchain_network
{
    echo "nameserver 8.8.8.8" > "$toolchain_root/etc/resolv.conf"
}

function toolchain_username
{
	cat <<- EOF > "$toolchain_root/etc/passwd"
		root:x:0:0:root:/root:/bin/bash
	EOF

	cat <<- EOF > "$toolchain_root/etc/group"
		root:x:0:
	EOF
}

function toolchain_archive
{
    toolchain_archive="$directory/toolchain/archive/toolchain.tar.gz"

    if [ ! -f "$toolchain_archive" ]
    then
        mkdir --parents "$(dirname "$toolchain_archive")"

        if ! tar                          \
            --create                      \
            --file "$toolchain_archive"   \
            --directory "$toolchain_root" \
            --gzip "."
        then
            echo "Error: Cannot create the toolchain archive."
            exit 1
        fi
    fi
}

function package_recipe
{
    package_recipe="$directory/recipe/$toolchain_package"

    if [ ! -f "$package_recipe" ]
    then
        echo "Error: Cannot read the package recipe for: $toolchain_package"
        exit 1
    fi

    source "$package_recipe"
}

function package_archive
{
    package_archive="$directory/package/archive/$(basename "$package_address")"

    if [ ! -f "$package_archive" ]
    then
        mkdir --parents "$(dirname "$package_archive")"

        if ! wget                              \
            --quiet                            \
            --show-progress "$package_address" \
            --output-document "$package_archive"
        then
            echo "Error: Cannot download the package archive for: $toolchain_package"
            exit 1
        fi
    fi
}

function package_source
{
    package_source="$directory/package/source/$toolchain_package"

    if [ ! -d "$package_source" ]
    then
        mkdir --parents "$package_source"

        if ! tar                          \
            --extract                     \
            --file "$package_archive"     \
            --directory "$package_source" \
            --strip-components 1
        then
            echo "Error: Cannot extract the package archive for: $toolchain_package"
            exit 1
        fi
    fi
}

function package_build
{
    package_build="$directory/package/build/$toolchain_package"

    if [ ! -d "$package_build" ]
    then
        mkdir --parents "$package_build"

        cd "$package_build"

        package_execute "do_configure"
        package_execute "do_build"
        package_execute "do_install"
    fi
}

function package_execute
{
    package_execute="$directory/package/execute/$toolchain_package"

    if [ ! -d "$package_execute" ]
    then
        mkdir --parents "$package_execute"
    fi

    echo "Execute: $toolchain_package - $1"

    if ! "$1"                    \
        1> "$package_execute/$1" \
        2> "$package_execute/$1"
    then
        echo "Error: Cannot execute the package recipe for: $toolchain_package"
        exit 1
    fi
}

function main
{
    directory

    toolchain_target
    toolchain_root

    toolchain_hostname
    toolchain_network
    toolchain_username

    export PATH="$toolchain_root/toolchain/bin:$PATH"

    for toolchain_package in \
        "01-binutils"        \
        "02-gcc"             \
        "03-linux-headers"   \
        "04-glibc"           \
        "05-libstdc++"       \
        "06-m4"              \
        "07-ncurses"         \
        "08-bash"            \
        "09-binutils"        \
        "10-coreutils"       \
        "11-diffutils"       \
        "12-findutils"       \
        "13-file"            \
        "14-gawk"            \
        "15-gcc"             \
        "16-grep"            \
        "17-gzip"            \
        "18-make"            \
        "19-patch"           \
        "20-sed"             \
        "21-tar"             \
        "22-xz"              \
        "23-zlib"            \
        "24-openssl"         \
        "25-wget"
    do
        package_recipe
        package_archive
        package_source
        package_build
    done

    toolchain_archive
}

main
