#!/bin/bash

package_name="ninja"
package_version="1.12.1"
package_address="https://github.com/ninja-build/$package_name/archive/refs/tags/v$package_version.tar.gz"
package_dependencies=""

function do_configure
{
    python3 "$package_source/configure.py" \
        --bootstrap
}

function do_build
{
    return
}

function do_install
{
    cp "$package_build/ninja" "$package_root/usr/bin/ninja"
}
