#!/bin/bash

package_name="dbus"
package_version="1.16.0"
package_address="https://dbus.freedesktop.org/releases/$package_name/$package_name-$package_version.tar.xz"
package_dependencies=""

function do_configure
{
    meson setup "$package_source" \
        --prefix="/usr"           \
        --libdir="/usr/lib"       \
        --buildtype="release"     \
        -D systemd="disabled"
}

function do_build
{
    ninja
}

function do_install
{
    DESTDIR="$package_root" ninja install
}
