#!/bin/bash

package_name="util-linux"
package_version="2.40.4"
package_address="https://www.kernel.org/pub/linux/utils/$package_name/v2.40/$package_name-$package_version.tar.xz"
package_dependencies=""

function do_configure
{
    "$package_source/configure"                                  \
        --bindir="/usr/bin"                                      \
        --docdir="/usr/share/doc/$package_name-$package_version" \
        --libdir="/usr/lib"                                      \
        --sbindir="/usr/sbin"                                    \
        --runstatedir="/run"                                     \
        --disable-chfn-chsh                                      \
        --disable-liblastlog2                                    \
        --disable-login                                          \
        --disable-nologin                                        \
        --disable-pylibmount                                     \
        --disable-runuser                                        \
        --disable-setpriv                                        \
        --disable-static                                         \
        --disable-su                                             \
        --without-python                                         \
        --without-systemd                                        \
        --without-systemdsystemunitdir                           \
        ADJTIME_PATH="/var/lib/hwclock/adjtime"
}

function do_build
{
    make
}

function do_install
{
    make DESTDIR="$package_root" install
}
