#!/bin/bash

package_name="inetutils"
package_version="2.6"
package_address="https://ftp.gnu.org/gnu/$package_name/$package_name-$package_version.tar.gz"
package_dependencies=""

function do_configure
{
    "$package_source/configure" \
        --prefix="/usr"         \
        --bindir="/usr/bin"     \
        --disable-logger        \
        --disable-rcp           \
        --disable-rexec         \
        --disable-rlogin        \
        --disable-rsh           \
        --disable-servers       \
        --disable-whois         \
        --localstatedir="/var"
}

function do_build
{
    make
}

function do_install
{
    make DESTDIR="$package_root" install
}
