#!/bin/bash

package_name="pixman"
package_version="0.44.2"
package_address="https://www.cairographics.org/releases/$package_name-$package_version.tar.gz"
package_dependencies=""

function do_configure
{
    meson setup "$package_source" \
        --prefix="/usr"           \
        --libdir="/usr/lib"       \
        --buildtype="release"
}

function do_build
{
    ninja
}

function do_install
{
    DESTDIR="$package_root" ninja install
}
