#!/bin/bash

package_name="sway"
package_version="1.10.1"
package_address="https://github.com/swaywm/$package_name/releases/download/$package_version/$package_name-$package_version.tar.gz"
package_dependencies=""

function do_configure
{
    meson setup "$package_source" \
        --prefix="/usr"           \
        --libdir="/usr/lib"       \
        --buildtype="release"
}

function do_build
{
    ninja
}

function do_install
{
    DESTDIR="$package_root" ninja install
}
