#!/bin/bash

package_name="bzip2"
package_version="1.0.8"
package_address="https://sourceware.org/pub/$package_name/$package_name-$package_version.tar.gz"
package_dependencies=""

function do_configure
{
    return
}

function do_build
{
    make --directory "$package_source"
}

function do_install
{
    make --directory "$package_source" DESTDIR="$package_root" PREFIX="/usr" install

    rm "$package_root/usr/lib/libbz2.a"
}
