#!/bin/bash

package_name="hwdata"
package_version="0.392"
package_address="https://github.com/vcrhonek/$package_name/archive/v$package_version/$package_name-$package_version.tar.gz"
package_dependencies=""

function do_configure
{
    cd "$package_source"

    "$package_source/configure" \
        --prefix="/usr"         \
        --disable-blacklist
}

function do_build
{
    return
}

function do_install
{
    make DESTDIR="$package_root" install
}
