#!/bin/bash

package_name="graphite2"
package_version="1.3.14"
package_address="https://github.com/silnrsi/graphite/releases/download/$package_version/$package_name-$package_version.tgz"
package_dependencies=""

function do_configure
{
    cmake "$package_source" \
        -D CMAKE_INSTALL_PREFIX="/usr"
}

function do_build
{
    make
}

function do_install
{
    make DESTDIR="$package_root" install
}
