#!/bin/bash

package_name="neovim"
package_version="0.11.1"
package_address="https://github.com/neovim/$package_name/archive/refs/tags/v$package_version.tar.gz"
package_dependencies=""

function do_configure
{
    make --directory="$package_source"    \
        CMAKE_INSTALL_PREFIX="/usr"       \
        CMAKE_BUILD_TYPE="RelWithDebInfo" \
        CMAKE_TLS_VERIFY="0"
}

function do_build
{
    return
}

function do_install
{
    make --directory="$package_source" DESTDIR="$package_root" install
}
