#!/bin/bash

package_name="libdisplay-info"
package_version="0.2.0"
package_address="https://gitlab.freedesktop.org/emersion/$package_name/-/releases/$package_version/downloads/$package_name-$package_version.tar.xz"
package_dependencies=""

function do_configure
{
    meson setup "$package_source" \
        --prefix="/usr"           \
        --libdir="/usr/lib"       \
        --buildtype="release"
}

function do_build
{
    ninja
}

function do_install
{
    DESTDIR="$package_root" ninja install
}
