#!/bin/bash

package_name="glib"
package_version="2.82.5"
package_address="https://download.gnome.org/sources/$package_name/2.82/$package_name-$package_version.tar.xz"
package_dependencies=""

function do_configure
{
    meson setup "$package_source"   \
        --prefix="/usr"             \
        --libdir="/lib"             \
        --buildtype="release"       \
        -D glib_debug="disabled"    \
        -D introspection="enabled"  \
        -D man-pages="enabled"      \
        -D sysprof="disabled"
}

function do_build
{
    ninja
}

function do_install
{
    DESTDIR="$package_root" ninja install
}
