#!/bin/bash

package_name="eudev"
package_version="3.2.14"
package_address="https://github.com/eudev-project/$package_name/releases/download/v$package_version/$package_name-$package_version.tar.gz"
package_dependencies=""

function do_configure
{
    "$package_source/configure" \
        --prefix="/usr"         \
        --bindir="/usr/sbin"    \
        --disable-static        \
        --enable-manpages       \
        --sysconfdir="/etc"
}

function do_build
{
    make
}

function do_install
{
    make DESTDIR="$package_root" install
}
