#!/bin/bash

package_name="elfutils"
package_version="0.192"
package_address="https://gcc.gnu.org/pub/$package_name/$package_version/$package_name-$package_version.tar.bz2"
package_dependencies=""

function do_configure
{
    "$package_source/configure" \
        --prefix="/usr"         \
        --disable-debuginfod    \
        --enable-libdebuginfod="dummy"
}

function do_build
{
    make
}

function do_install
{
    make --directory "$package_build/libelf" DESTDIR="$package_root" install

    rm "$package_root/usr/lib/libelf.a"
}
