#!/bin/bash

package_name="libdrm"
package_version="2.4.124"
package_address="https://dri.freedesktop.org/$package_name/$package_name-$package_version.tar.xz"
package_dependencies=""

function do_configure
{
    meson setup "$package_source" \
        --prefix="/usr"           \
        --libdir="/usr/lib"       \
        --buildtype="release"     \
        -D udev="true"            \
        -D valgrind="disabled"
}

function do_build
{
    ninja
}

function do_install
{
    DESTDIR="$package_root" ninja install
}
