#!/bin/bash

package_name="glibc"
package_version="2.41"
package_address="https://ftp.gnu.org/gnu/$package_name/$package_name-$package_version.tar.gz"
package_dependencies=""

function do_configure
{
    ln --symbolic "$package_root/lib/ld-linux-x86-64.so.2" \
       --relative "$package_root/lib64"

    echo "rootsbindir=/usr/sbin" > "$package_build/configparms"

    "$package_source/configure"           \
        --prefix="/usr"                   \
        --disable-nscd                    \
        --disable-werror                  \
        --enable-kernel="5.4"             \
        --enable-stack-protector="strong" \
        libc_cv_slibdir="/usr/lib"
}

function do_build
{
    make
}

function do_install
{
    make DESTDIR="$package_root" install
}
