#!/bin/bash

package_name="libffi"
package_version="3.4.7"
package_address="https://github.com/libffi/$package_name/releases/download/v$package_version/$package_name-$package_version.tar.gz"
package_dependencies=""

function do_configure
{
    "$package_source/configure" \
        --prefix="/usr"         \
        --disable-static        \
        --with-gcc-arch="native"
}

function do_build
{
    make
}

function do_install
{
    make DESTDIR="$package_root" install
}
