#!/bin/bash

package_name="libpng"
package_version="1.6.46"
package_address="https://downloads.sourceforge.net/$package_name/$package_name-$package_version.tar.xz"
package_dependencies=""

function do_configure
{
    "$package_source/configure" \
        --prefix="/usr"         \
        --disable-static
}

function do_build
{
    make
}

function do_install
{
    make DESTDIR="$package_root" install
}
