#!/bin/bash

package_name="pkgconf"
package_version="2.3.0"
package_address="https://distfiles.ariadne.space/$package_name/$package_name-$package_version.tar.xz"
package_dependencies=""

function do_configure
{
    "$package_source/configure"                                  \
        --prefix="/usr"                                          \
        --docdir="/usr/share/doc/$package_name-$package_version" \
        --disable-static
}

function do_build
{
    make
}

function do_install
{
    make DESTDIR="$package_root" install

    ln --symbolic "$package_root/usr/bin/pkgconf" \
       --relative "$package_root/usr/bin/pkg-config"
}
