#!/bin/bash

package_name="grep"
package_version="3.11"
package_address="https://ftp.gnu.org/gnu/$package_name/$package_name-$package_version.tar.gz"
package_dependencies=""

function do_configure
{
    "$package_source/configure" \
        --prefix="/usr"
}

function do_build
{
    make
}

function do_install
{
    make DESTDIR="$package_root" install
}
