#!/bin/bash

package_name="shared-mime-info"
package_version="2.4"
package_address="https://gitlab.freedesktop.org/xdg/$package_name/-/archive/$package_version/$package_name-$package_version.tar.gz"
package_dependencies=""

function do_configure
{
    meson setup "$package_source" \
        --prefix="/usr"           \
        --libdir="/usr/lib"       \
        --buildtype="release"     \
        -D update-mimedb="true"
}

function do_build
{
    ninja
}

function do_install
{
    DESTDIR="$package_root" ninja install
}
