#!/bin/bash

package_name="seatd"
package_version="0.9.1"
package_address="https://git.sr.ht/~kennylevinsen/$package_name/archive/$package_version.tar.gz"
package_dependencies=""

function do_configure
{
    meson setup "$package_source" \
        --prefix="/usr"           \
        --libdir="/usr/lib"       \
        --buildtype="release"
}

function do_build
{
    ninja
}

function do_install
{
    DESTDIR="$package_root" ninja install
}
